using FranqueadoraService as service from '../../srv/service';

// ─────────────────────────────────────────────────────────────
// REPLENISHMENT ORDERS — List Report + Object Page
// Manager approves/rejects orders generated by the AI Replenishment Agent.
// ─────────────────────────────────────────────────────────────

annotate service.Pedidos_Reposicao with @(

  // ── Filters ───────────────────────────────────────────────
  UI.SelectionFields: [ regiaoCode, status_code, origem_code ],

  // ── Presentation: sort by urgency first, then by desired date ──
  UI.PresentationVariant: {
    SortOrder     : [
      { Property: urgenciaCriticality, Descending: false },
      { Property: prazoDesejado,       Descending: false }
    ],
    Visualizations: [ '@UI.LineItem' ]
  }

) {
  status @(
    Common.ValueListWithFixedValues: true,
    Common.ValueList: {
      CollectionPath: 'StatusPedidoRep',
      Parameters: [
        { $Type: 'Common.ValueListParameterOut',
          LocalDataProperty: status_code, ValueListProperty: 'code' },
        { $Type: 'Common.ValueListParameterDisplayOnly',
          ValueListProperty: 'name' }
      ]
    }
  );
  regiaoCode @(
    title: 'Region',
    Common.ValueListWithFixedValues: true,
    Common.ValueList: {
      CollectionPath: 'Regiao',
      Parameters: [
        { $Type: 'Common.ValueListParameterOut',
          LocalDataProperty: regiaoCode, ValueListProperty: 'code' },
        { $Type: 'Common.ValueListParameterDisplayOnly',
          ValueListProperty: 'name' }
      ]
    }
  );
  origem @(
    title: 'Origin',
    Common.ValueListWithFixedValues: true,
    Common.ValueList: {
      CollectionPath: 'OrigemPedido',
      Parameters: [
        { $Type: 'Common.ValueListParameterOut',
          LocalDataProperty: origem_code, ValueListProperty: 'code' },
        { $Type: 'Common.ValueListParameterDisplayOnly',
          ValueListProperty: 'name' }
      ]
    }
  );
}

annotate service.Pedidos_Reposicao with @(

  // ── DataPoint: urgency with criticality ──────────────────
  UI.DataPoint #Urgencia: {
    Value       : status_code,
    Title       : 'Status',
    Criticality : urgenciaCriticality
  },

  // ── Table (List Report) ───────────────────────────────────
  UI.LineItem: [
    { Value: unidadeNome,   Label: 'Store',    ![@UI.Importance]: #High },
    { Value: regiaoCode,    Label: 'Region',   ![@UI.Importance]: #Medium },
    { Value: sku,           Label: 'SKU' },
    { Value: nomeProduto,   Label: 'Product',  ![@UI.Importance]: #High },
    { Value: qtdSugerida,   Label: 'Suggested Qty', ![@UI.Importance]: #High },
    { Value: qtdAprovada,   Label: 'Approved Qty' },
    {
      $Type : 'UI.DataFieldForAnnotation',
      Target: '@UI.DataPoint#Urgencia',
      Label : 'Status',
      ![@UI.Importance]: #High
    },
    { Value: prazoDesejado, Label: 'Desired Date' },
    { Value: origemLabel,   Label: 'Origin' },
    {
      $Type  : 'UI.DataFieldForAction',
      Action : 'FranqueadoraService.Pedidos_Reposicao_aprovar',
      Label  : 'Approve',
      ![@UI.Importance]: #High
    },
    {
      $Type  : 'UI.DataFieldForAction',
      Action : 'FranqueadoraService.Pedidos_Reposicao_recusar',
      Label  : 'Reject'
    }
  ],

  // ── Object Page ───────────────────────────────────────────
  UI.HeaderInfo: {
    TypeName       : 'Replenishment Order',
    TypeNamePlural : 'Replenishment Orders',
    Title          : { Value: nomeProduto },
    Description    : { Value: unidadeNome }
  },

  UI.FieldGroup #Pedido: {
    Label: 'Order Details',
    Data : [
      { $Type: 'UI.DataFieldForAnnotation', Target: '@UI.DataPoint#Urgencia', Label: 'Status' },
      { Value: qtdSugerida,        Label: 'Suggested Qty' },
      { Value: qtdAprovada,        Label: 'Approved Qty' },
      { Value: fornecedorSugerido, Label: 'Suggested Supplier' },
      { Value: prazoDesejado,      Label: 'Desired Date' },
      { Value: origemLabel,        Label: 'Origin' }
    ]
  },

  UI.FieldGroup #Loja: {
    Label: 'Store',
    Data : [
      { Value: unidadeNome,   Label: 'Store' },
      { Value: unidadeCidade, Label: 'City' },
      { Value: regiaoCode,    Label: 'Region' },
      { Value: sku,           Label: 'SKU' },
      { Value: nomeProduto,   Label: 'Product' }
    ]
  },

  UI.FieldGroup #Decisao: {
    Label: 'Decision',
    Data : [
      { Value: aprovador,   Label: 'Approver' },
      { Value: dataDecisao, Label: 'Decision Date' }
    ]
  },

  UI.FieldGroup #Justificativa: {
    Label: 'AI Agent Rationale',
    Data : [
      { Value: justificativa, Label: 'Rationale', ![@UI.MultiLineText]: true }
    ]
  },

  UI.Facets: [
    {
      $Type : 'UI.ReferenceFacet',
      Target: '@UI.FieldGroup#Pedido',
      Label : 'Order Details'
    },
    {
      $Type : 'UI.ReferenceFacet',
      Target: '@UI.FieldGroup#Loja',
      Label : 'Store'
    },
    {
      $Type : 'UI.ReferenceFacet',
      Target: '@UI.FieldGroup#Justificativa',
      Label : 'AI Agent Rationale'
    },
    {
      $Type : 'UI.ReferenceFacet',
      Target: '@UI.FieldGroup#Decisao',
      Label : 'Decision'
    }
  ],

  // ── Actions on Object Page ────────────────────────────────
  UI.Identification: [
    {
      $Type  : 'UI.DataFieldForAction',
      Action : 'FranqueadoraService.Pedidos_Reposicao_aprovar',
      Label  : 'Approve'
    },
    {
      $Type  : 'UI.DataFieldForAction',
      Action : 'FranqueadoraService.Pedidos_Reposicao_recusar',
      Label  : 'Reject'
    }
  ]
);
